(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.product = function() {
	this.initialize(img.product);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.text3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDADIAAgDIABgCIACgBIADABIABACIgBADIgDABIgDgBg");
	this.shape.setTransform(189.9,21.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgCgDIgEgHIgBgLIABgKIAEgHIAFgEQADgCAEAAQAFAAADACQADABACADIACAGIABAIIAAADIgBACIgbAAIABAIQAAADACACQACACADABIAHABIAGAAIAEgBIABABIABAAIAAADIgGABIgIABQgDAAgFgCgAgEgRQgCABgCADIgCAFIgBAHIAXAAIABgBIAAgCIgBgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_1.setTransform(186.5,20);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFAWQgDgCgCgDQgCgDAAgFIgCgJQAAgMAFgFQAFgGAHABIADAAIADAAIACABIACAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgFAAIgEABQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABQgCACgBADIgBAJIABAJIADAGQACADADAAIADABIAGgBIAEAAIABAAIABABIAAADIgGABIgGABQgEAAgEgCg");
	this.shape_2.setTransform(182.3,20.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_3.setTransform(179.2,19.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_4.setTransform(176.8,20);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_5.setTransform(172.6,20.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIAAgDIAAggIgEAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_6.setTransform(166.6,19.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAIAAIADgBIABABIABAAIAAADIgGABIgIABQgEAAgEgCgAgEgRQgDABgBADIgCAFIgBAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_7.setTransform(162.8,20);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFAWQgEgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQADABACADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAIAAIADgBIABABIAAAAIAAADIgFABIgIABQgDAAgEgCgAgEgRQgDABgBADIgDAFIAAAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIgFgBQgDAAgCABg");
	this.shape_8.setTransform(158.2,20);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_9.setTransform(154.4,20);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAAdIgCgCIgCgEIAAgDIAAggIgFAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIAAABIADABIADAAIACAAIABAAIACABIAAABIAAADIgGAAIgFAAg");
	this.shape_10.setTransform(151.1,19.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgDAXIgDAAIgEAAIgCgBQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGABIAHABIAFgBIAEgCIACgCIABgEIgCgEIgCgCIgDgBIgFgCIgFgBIgFgCIgCgDIgBgGQAAgFADgDQAEgDAHAAIADAAIADAAIADAAIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgGAAIgEAAIgEABIgCADIgBADIABADIACADIAEACIAEABIAFABIAFABIADAFQACACgBADQAAAHgEAEQgEADgHAAIgDgBg");
	this.shape_11.setTransform(147.5,20.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJAfQgCgCgDgDIgCgHIgBgKQABgMAEgFQAFgGAHAAIAIABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAA/IgDAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgEACgDAAQgFAAgEgCgAgEgIQgCABgCACQgCACAAADIgBAJQAAAKACAEQADAFAGAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgHgBIgFABg");
	this.shape_12.setTransform(140.9,19.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgFAWQgEgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQADgCAEAAQAFAAADACQADABACADIACAGIABAIIAAADIgBACIgbAAIABAIQABADABACQACACADABIAHABIAHAAIADgBIABABIAAAAIAAADIgFABIgHABQgFAAgDgCgAgEgRQgDABgBADIgDAFIAAAHIAXAAIABgBIAAgCIgBgGQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIgFgBQgDAAgCABg");
	this.shape_13.setTransform(136.3,20);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_14.setTransform(132.4,19.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgMATQgEgDAAgHQAAgIAFgCQAEgDAHAAIAMAAIAAgEIgBgEIgCgEIgEgCIgFAAIgHAAIgEABQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAIABIAGACQACACAAAEIABAFIAAAfIgDAAQgBAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgDACIgDADIgEABIgEABQgHAAgDgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABgBAAIgCAEIAAADQAAAFACADQADACAFAAQADAAAEgCQADgBADgDIAAgNIgMAAIgFAAg");
	this.shape_15.setTransform(128.5,20.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAbAXQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgCgDgFAAIgEABIgEACIgDACIgCACIAAACIAAADIAAAdIgCAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgcQAAgGgCgDQgDgDgFAAIgDABIgEABIgDADIgCACIAAAiIgEAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgrIAEAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAEIABgCIAEgCIAEgBIAFgBQAEAAADACQADABABAEIACgCIADgDIAFgBIAGgBQAGAAAEAEQADADAAAJIAAAdg");
	this.shape_16.setTransform(122.6,20);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_17.setTransform(117.8,19.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_18.setTransform(115.3,19.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgDAXIgDAAIgEAAIgDgBQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGABIAHABIAFgBIAEgCIACgCIABgEIgBgEIgDgCIgEgBIgEgCIgFgBIgFgCIgDgDIAAgGQAAgFADgDQAEgDAHAAIADAAIACAAIAEAAIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgGAAIgFAAIgDABIgCADIgBADIABADIACADIADACIAFABIAFABIAFABIADAFQABACAAADQABAHgFAEQgEADgHAAIgDgBg");
	this.shape_19.setTransform(111.7,20.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgFAWQgEgBgCgDIgEgHIgBgLIABgKIAEgHIAFgEQAEgCADAAQAFAAADACQADABACADIACAGIABAIIAAADIgBACIgbAAIABAIQABADABACQACACADABIAHABIAGAAIAEgBIABABIABAAIAAADIgGABIgHABQgFAAgDgCgAgEgRQgCABgCADIgDAFIAAAHIAXAAIABgBIAAgCIgBgGQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_20.setTransform(107.4,20);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAHAAIAEgBIABABIABAAIAAADIgGABIgIABQgEAAgEgCgAgEgRQgDABgBADIgCAFIgBAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_21.setTransform(100.7,20);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AANAgQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgdQAAgFgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg+IAEAAIABABIAAAXIAGgEQADgCAFAAQAGAAAEAEQAEADAAAIIAAAeg");
	this.shape_22.setTransform(96,19.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_23.setTransform(92,19.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAAAdIgCgCIgCgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIAAABIACABIAEAAIACAAIABAAIABABIABABIAAADIgHAAIgEAAg");
	this.shape_24.setTransform(86.8,19.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgNATQgDgDAAgHQAAgIAEgCQAFgDAHAAIAMAAIAAgEIgBgEIgCgEIgEgCIgFAAIgHAAIgFABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAJABIAEACQACACABAEIABAFIAAAfIgEAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgCACIgEADIgEABIgEABQgHAAgEgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAIgDAEIAAADQAAAFADADQADACAEAAQAEAAADgCQAEgBACgDIAAgNIgMAAIgFAAg");
	this.shape_25.setTransform(82.9,20.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgDAXIgEAAIgDAAIgCgBQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGABIAHABIAFgBIAEgCIACgCIAAgEIgBgEIgCgCIgEgBIgEgCIgFgBIgEgCIgEgDIgBgGQAAgFAFgDQADgDAHAAIACAAIAEAAIADAAIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgGAAIgEAAIgEABIgCADIAAADIAAADIACADIAEACIAEABIAGABIAEABIADAFQABACABADQgBAHgEAEQgEADgHAAIgDgBg");
	this.shape_26.setTransform(76.6,20.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQADABACADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAIAAIADgBIABABIAAAAIAAADIgFABIgIABQgDAAgFgCgAgEgRQgDABgBADIgDAFIAAAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIgFgBQgDAAgCABg");
	this.shape_27.setTransform(72.2,20);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgHAfIgGgBQAAgBgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgDIAHABIAHABIAFgBIAEgDIACgDIAAgFIAAgEIgFACQgDACgDAAQgIAAgFgGQgEgFAAgKQABgIABgEQABgFADgCQACgDAEgBIAIgBIAEAAIAEAAIAEABIADAAIABABIAAABIAAACIgCAAIAAAoQAAAIgFAEQgDAEgIAAIgHAAgAgEgZIgFADQgBACgBAEIgBAKQAAAIADAEQADAFAGAAQACgBAEgBIAEgDIAAgfIgDAAIgGAAIgFAAg");
	this.shape_28.setTransform(67.6,20.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgIAfQgEgCgBgDIgDgHIAAgKQgBgMAFgFQAFgGAIAAIAHABIAFACIAAgVIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgGAEQgDACgFAAQgEAAgDgCgAgEgIQgDABgBACQgCACgBADIgBAJQABAKACAEQADAFAGAAIADAAIAEgCIADgCIADgCIAAgdIgGgBIgFgBIgGABg");
	this.shape_29.setTransform(62.7,19.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_30.setTransform(59.3,19.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_31.setTransform(56.9,20);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIAAgDIAAggIgFAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgGAAIgFAAg");
	this.shape_32.setTransform(53.6,19.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_33.setTransform(50.6,20);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNATQgDgDAAgHQAAgIAEgCQAFgDAHAAIAMAAIAAgEIgBgEIgCgEIgEgCIgFAAIgHAAIgFABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAJABIAEACQACACABAEIABAFIAAAfIgEAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgCACIgEADIgEABIgEABQgHAAgEgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAIgDAEIAAADQAAAFADADQADACAEAAQAEAAADgCQAEgBACgDIAAgNIgMAAIgFAAg");
	this.shape_34.setTransform(46.5,20.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgFAWQgDgCgCgDQgCgDgBgFIAAgJQAAgMAEgFQAEgGAIABIADAAIADAAIADABIABAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgFgBIgGAAIgEABQgCABgCACQgCACAAADIgBAJIABAJIACAGQACADACAAIAEABIAHgBIADAAIABAAIAAABIAAADIgFABIgGABQgEAAgEgCg");
	this.shape_35.setTransform(42.4,20.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgDAeQgCgCAAgEIAAg4IAEAAIABABIAAA3IAAAEIADAAIACAAIABABIAAAAIAAACIgCABIgDAAQgCAAgCgCg");
	this.shape_36.setTransform(37.3,19.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgNATQgDgDAAgHQAAgIAEgCQAFgDAHAAIALAAIAAgEIAAgEIgCgEIgEgCIgFAAIgHAAIgFABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAJABIAEACQACACABAEIABAFIAAAfIgEAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgCACIgEADIgEABIgDABQgIAAgEgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAIgCAEIgBADQAAAFADADQADACAEAAQADAAAEgCQADgBACgDIAAgNIgLAAIgFAAg");
	this.shape_37.setTransform(33.6,20.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgIIAAgeIADAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAcQAAAHADACQADADAEAAIAEgBIADgBIAEgCIACgCIAAgjIADAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAArIgEAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIgCACIgEACIgEACIgEAAQgGAAgFgDg");
	this.shape_38.setTransform(29,20.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgIAfQgDgCgDgDIgCgHIAAgKQAAgMAEgFQAFgGAIAAIAHABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgDACgEAAQgGAAgCgCgAgEgIQgDABgBACQgCACAAADIgCAJQAAAKADAEQACAFAHAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgHgBIgFABg");
	this.shape_39.setTransform(24.2,19.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_40.setTransform(20.8,19.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAAAXIgCgBIAAgBIgFgKIgFgLIgCgKIgDgMIAEAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQACAKAEAKQADAKAEAIIADgJIAEgJIADgLIACgLIAEAAIABABIAAABIgCALIgEAKIgEALIgFALg");
	this.shape_41.setTransform(17.7,20);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_42.setTransform(14.5,19.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgIAfQgDgCgDgDIgCgHIAAgKQAAgMAEgFQAFgGAIAAIAHABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgDACgEAAQgGAAgCgCgAgEgIQgDABgBACQgCACAAADIgCAJQAAAKADAEQADAFAGAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgGgBIgGABg");
	this.shape_43.setTransform(11.1,19.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AANAXQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIACgCIADgCIAFgBIAEgBQAGAAAEAEQAEADAAAJIAAAdg");
	this.shape_44.setTransform(6.4,20);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_45.setTransform(2.9,19.2);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgGAeIgHgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAgCIAHABIAHAAIAFAAIAEgCIACgEIABgEIAAgGIgGAEQgDABgDAAQgJAAgEgGQgDgGAAgKQAAgGABgFQABgEADgDQADgDADgBIAIgBIAEAAIAEABIAEAAIADABIABAAIABABIAAACIgEAAIAAApQAAAHgDAEQgEAEgIAAIgGgBgAgEgZIgEADQgCACgCAEIgBAJQAAAJAEAFQADADAGAAQACABADgCIAGgDIAAgfIgFgBIgEAAIgGABg");
	this.shape_46.setTransform(178.4,9.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AANAXQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIACgCIADgCIAFgBIAEgBQAGAAAEAEQAEADAAAJIAAAdg");
	this.shape_47.setTransform(173.6,8.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBIADABIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_48.setTransform(170.1,7.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgDAXIgEAAIgDgBIgCAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIAGABIAHAAIAFAAIAEgCIACgDIAAgDIgBgFIgCgCIgDgBIgFgCIgFgBIgEgCIgDgDIgCgGQABgFAEgEQADgDAHAAIACAAIAEAAIADABIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgGAAIgEAAIgEACIgCACIAAADIAAAEIACACIAEABIAEACIAGACIAEABIADADQABADABAEQgBAGgEAEQgEACgHAAIgDAAg");
	this.shape_49.setTransform(167.1,8.8);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgMAUQgEgEAAgHQAAgHAFgDQAEgDAHAAIAMAAIAAgDIgBgGIgCgDIgEgBIgFgBIgHABIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAIABIAGAEQACACAAACIABAHIAAAdIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgDACIgDABIgEACIgEAAQgHAAgDgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAIgBADIgBAEQAAAGACACQADACAFAAQADAAAEgCQADgBADgDIAAgNIgMAAIgFAAg");
	this.shape_50.setTransform(162.7,8.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AANAgQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgdQAAgFgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg+IAEAAIABABIAAAXIAGgEQADgCAFAAQAGAAAEAEQAEADAAAIIAAAeg");
	this.shape_51.setTransform(158.1,7.8);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgFAVQgDgBgCgDQgCgDgBgEIgBgKQAAgLAFgGQAFgFAHgBIADAAIADABIACAAIACABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgFgBIgGAAIgEABQgCAAgCADQgCACgBAEIAAAIIAAAKIADAFQACACADABIADABIAHAAIADgBIABABIABAAIAAACIgGACIgGAAQgEAAgEgCg");
	this.shape_52.setTransform(153.9,8.8);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_53.setTransform(150.4,8.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgIIAAgeIADAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAcQAAAHADACQADADAEAAIADgBIAFgBIACgCIADgCIAAgjIAEAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAArIgEAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIgDACIgCACIgFACIgEAAQgGAAgFgDg");
	this.shape_54.setTransform(146.2,8.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_55.setTransform(141.3,9.5);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgNASQgEgGAAgMQAAgLAEgGQAEgGAJAAQAKAAAEAGQAEAGAAALQAAAMgEAGQgEAGgKAAQgJAAgEgGgAgFgRQgCABgCACQgCACAAAEIgBAIIABAJQAAAEACACIAEADIAFABIAGgBIAEgDIACgGIABgJIgBgIQAAgEgCgCIgEgDIgGgBIgFABg");
	this.shape_56.setTransform(134.5,8.7);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAAAcIgDgBIgBgDIAAgEIAAgfIgFAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAEIgLAAIAAAeIAAACIABADIACABIADAAIACAAIABAAIACAAIAAABIAAACIgHABIgEgBg");
	this.shape_57.setTransform(130.5,8.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgIAfQgEgCgCgDIgCgHIAAgKQgBgMAFgFQAFgGAIAAIAHABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgDACgEAAQgGAAgCgCgAgEgIQgDABgBACQgCACgBADIgBAJQAAAKADAEQADAFAGAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgGgBIgGABg");
	this.shape_58.setTransform(124.4,7.8);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgCgDIgEgHIgBgLIABgKIAEgHIAFgEQADgCAEAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAACIgcAAIABAIQAAADACACQACACADABIAGABIAHAAIAEgBIABABIABAAIAAADIgGABIgIABQgDAAgFgCgAgEgRQgCABgCADIgCAFIgBAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_59.setTransform(119.8,8.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_60.setTransform(116,8.7);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgHQAAgHAEgDQAFgDAHAAIALAAIAAgDIAAgGIgCgDIgEgBIgFgBIgHABIgFAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAJABIAEAEQACACABACIABAHIAAAdIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgCACIgEABIgEACIgDAAQgIAAgEgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAAAIgCADIgBAEQAAAGADACQADACAEAAQADAAAEgCQADgBACgDIAAgNIgLAAIgFAAg");
	this.shape_61.setTransform(111.9,8.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_62.setTransform(107.2,9.5);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AAbAXQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgCgDgEAAIgFABIgEACIgDACIgCACIAAACIAAADIAAAdIgCAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgFABIgDABIgDADIgDACIAAAiIgDAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAEIACgCIAEgCIAEgBIAFgBQAEAAADACQADABABAEIACgCIAEgDIAEgBIAGgBQAGAAAEAEQADADAAAJIAAAdg");
	this.shape_63.setTransform(101.2,8.7);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgNASQgEgGAAgMQAAgLAEgGQAEgGAJAAQAKAAAEAGQAEAGAAALQAAAMgEAGQgEAGgKAAQgJAAgEgGgAgFgRQgCABgCACQgCACAAAEIgBAIIABAJQAAAEACACIAEADIAFABIAGgBIAEgDIACgGIABgJIgBgIQAAgEgCgCQgCgCgCgBIgGgBIgFABg");
	this.shape_64.setTransform(95,8.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AgFAVQgDgBgCgDQgCgDgBgEIgBgKQABgLAEgGQAFgFAHgBIADAAIADABIACAAIACABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgFgBIgGAAIgEABQgCAAgCADQgCACAAAEIgBAIIABAKIACAFQACACADABIADABIAHAAIADgBIABABIAAAAIAAACIgFACIgGAAQgEAAgEgCg");
	this.shape_65.setTransform(90.8,8.8);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgDAXIgEAAIgDgBIgDAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIAGABIAHAAIAFAAIAEgCIACgDIAAgDIAAgFIgDgCIgEgBIgEgCIgFgBIgEgCIgEgDIgBgGQAAgFAFgEQADgDAHAAIACAAIAEAAIADABIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgGAAIgFAAIgDACIgCACIAAADIAAAEIACACIADABIAFACIAGACIAEABIADADQACADAAAEQAAAGgFAEQgEACgHAAIgDAAg");
	this.shape_66.setTransform(84.6,8.8);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgHAeIgGgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAgCIAHABIAHAAIAFAAIAEgCIACgEIAAgEIAAgGIgFAEQgDABgDAAQgIAAgFgGQgEgGAAgKQABgGABgFQABgEADgDQACgDAEgBIAIgBIAEAAIAEABIAEAAIADABIABAAIAAABIAAACIgCAAIAAApQAAAHgFAEQgDAEgIAAIgHgBgAgEgZIgFADQgBACgBAEIgBAJQAAAJADAFQADADAGAAQACABAEgCIAEgDIAAgfIgDgBIgGAAIgFABg");
	this.shape_67.setTransform(80.2,9.5);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AANAXQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIACgCIADgCIAFgBIAEgBQAGAAAEAEQAEADAAAJIAAAdg");
	this.shape_68.setTransform(75.3,8.7);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIACgBIADABIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_69.setTransform(71.9,7.9);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AAAAXIgCgBIAAgBIgFgKIgFgLIgCgKIgDgMIAFAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQACAKAEAKQADAKADAIIAFgJIADgJIADgLIACgLIAEAAIABABIAAABIgCALIgDAKIgFALIgFALg");
	this.shape_70.setTransform(68.8,8.7);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgHQAAgHAFgDQAEgDAHAAIALAAIAAgDIAAgGIgCgDIgEgBIgFgBIgHABIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAJABIAEAEQADACAAACIABAHIAAAdIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgCACIgEABIgEACIgDAAQgIAAgEgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAAAIgCADIgBAEQAAAGADACQADACAEAAQAEAAADgCQADgBACgDIAAgNIgLAAIgFAAg");
	this.shape_71.setTransform(64.3,8.8);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AgDAXIgDAAIgEgBIgDAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIAGABIAHAAIAFAAIAEgCIACgDIABgDIgBgFIgDgCIgEgBIgEgCIgFgBIgFgCIgDgDIAAgGQgBgFAEgEQAEgDAHAAIACAAIADAAIAEABIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgGAAIgFAAIgDACIgCACIAAADIAAAEIACACIADABIAFACIAFACIAFABIADADQABADAAAEQABAGgFAEQgEACgHAAIgDAAg");
	this.shape_72.setTransform(60.1,8.8);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AAMAgIgCgBIgJgKIgMgLIAAAWIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg+IAEAAIABABIAAAkQAHgEAFgEIAJgKIADAAIABABIAAABIgBABIgDAEIgFAEIgFAEIgGAFIAHAGIAGAGIAFAGIAFAGg");
	this.shape_73.setTransform(53.9,7.8);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AgEAVQgEgBgCgDQgCgDAAgEIgBgKQgBgLAFgGQAEgFAIgBIADAAIADABIACAAIACABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgEAAIgFABQgDAAgBADQgCACgBAEIgBAIIABAKIADAFQACACACABIAFABIAFAAIAEgBIABABIABAAIAAACIgGACIgGAAQgEAAgDgCg");
	this.shape_74.setTransform(49.7,8.8);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgMAUQgEgEAAgHQAAgHAFgDQAEgDAHAAIAMAAIAAgDIgBgGIgCgDIgEgBIgFgBIgHABIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAIABIAGAEQACACAAACIABAHIAAAdIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgDACIgDABIgEACIgEAAQgHAAgDgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAIgCADIAAAEQAAAGACACQADACAFAAQADAAAEgCQADgBADgDIAAgNIgMAAIgFAAg");
	this.shape_75.setTransform(45.3,8.8);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_76.setTransform(40.6,9.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgLACIgBgBIAAgCIAYAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAACg");
	this.shape_77.setTransform(36.4,8.5);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIABgDIACgBIADABIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_78.setTransform(33.6,7.9);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AAAAcIgDgBIgBgDIAAgEIAAgfIgFAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAEIgLAAIAAAeIAAACIABADIACABIADAAIACAAIABAAIACAAIAAABIAAACIgGABIgFgBg");
	this.shape_79.setTransform(31.1,8.2);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgDAeQgCgCAAgEIAAg3IAEAAIABABIAAA2IAAADIADABIACAAIABAAIAAABIAAADIgCAAIgDABQgCgBgCgCg");
	this.shape_80.setTransform(28.5,7.8);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgMAUQgEgEAAgIIAAgeIAEAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAcQAAAHADACQACADAFAAIADgBIAFgBIACgCIADgCIAAgjIAEAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAArIgDAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIgDACIgCACIgFACIgEAAQgGAAgEgDg");
	this.shape_81.setTransform(24.8,8.8);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AAVAfQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgNIAAgNIAAgMIgBgNIgPAkIgEAAIgBAAIgBgBIgOgjIAAANIgBANIAAANIgBANIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIABgeIABgeIAFAAIABABIAQAnIASgoIADAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIACAeIABAeg");
	this.shape_82.setTransform(19.2,7.9);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AgJANIAAgCIABgBIAHgIIgNgDIABgDIABgBIACABIAKADIgBgMIACAAIABABIAAABIAAAKIAMgEIABADIAAABIgCABIgKACIAIAKIgDACIgBAAIgBgBIgGgJIgGALg");
	this.shape_83.setTransform(14.1,6.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgDADIAAgDIABgCIACgBIADABIABACIgBADIgDABIgDgBg");
	this.shape_84.setTransform(189.9,21.9);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgCgDIgEgHIgBgLIABgKIAEgHIAFgEQADgCAEAAQAFAAADACQADABACADIACAGIABAIIAAADIgBACIgbAAIABAIQAAADACACQACACADABIAHABIAGAAIAEgBIABABIABAAIAAADIgGABIgIABQgDAAgFgCgAgEgRQgCABgCADIgCAFIgBAHIAXAAIABgBIAAgCIgBgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_85.setTransform(186.5,20);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AgFAWQgDgCgCgDQgCgDAAgFIgCgJQAAgMAFgFQAFgGAHABIADAAIADAAIACABIACAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgFAAIgEABQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABQgCACgBADIgBAJIABAJIADAGQACADADAAIADABIAGgBIAEAAIABAAIABABIAAADIgGABIgGABQgEAAgEgCg");
	this.shape_86.setTransform(182.3,20.1);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_87.setTransform(179.2,19.2);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_88.setTransform(176.8,20);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_89.setTransform(172.6,20.8);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIAAgDIAAggIgEAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_90.setTransform(166.6,19.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAIAAIADgBIABABIABAAIAAADIgGABIgIABQgEAAgEgCgAgEgRQgDABgBADIgCAFIgBAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_91.setTransform(162.8,20);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgFAWQgEgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQADABACADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAIAAIADgBIABABIAAAAIAAADIgFABIgIABQgDAAgEgCgAgEgRQgDABgBADIgDAFIAAAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIgFgBQgDAAgCABg");
	this.shape_92.setTransform(158.2,20);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_93.setTransform(154.4,20);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AAAAdIgCgCIgCgEIAAgDIAAggIgFAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIAAABIADABIADAAIACAAIABAAIACABIAAABIAAADIgGAAIgFAAg");
	this.shape_94.setTransform(151.1,19.5);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AgDAXIgDAAIgEAAIgCgBQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGABIAHABIAFgBIAEgCIACgCIABgEIgCgEIgCgCIgDgBIgFgCIgFgBIgFgCIgCgDIgBgGQAAgFADgDQAEgDAHAAIADAAIADAAIADAAIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgGAAIgEAAIgEABIgCADIgBADIABADIACADIAEACIAEABIAFABIAFABIADAFQACACgBADQAAAHgEAEQgEADgHAAIgDgBg");
	this.shape_95.setTransform(147.5,20.1);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AgJAfQgCgCgDgDIgCgHIgBgKQABgMAEgFQAFgGAHAAIAIABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAA/IgDAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgEACgDAAQgFAAgEgCgAgEgIQgCABgCACQgCACAAADIgBAJQAAAKACAEQADAFAGAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgHgBIgFABg");
	this.shape_96.setTransform(140.9,19.1);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FFFFFF").s().p("AgFAWQgEgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQADgCAEAAQAFAAADACQADABACADIACAGIABAIIAAADIgBACIgbAAIABAIQABADABACQACACADABIAHABIAHAAIADgBIABABIAAAAIAAADIgFABIgHABQgFAAgDgCgAgEgRQgDABgBADIgDAFIAAAHIAXAAIABgBIAAgCIgBgGQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIgFgBQgDAAgCABg");
	this.shape_97.setTransform(136.3,20);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_98.setTransform(132.4,19.5);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#FFFFFF").s().p("AgMATQgEgDAAgHQAAgIAFgCQAEgDAHAAIAMAAIAAgEIgBgEIgCgEIgEgCIgFAAIgHAAIgEABQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAIABIAGACQACACAAAEIABAFIAAAfIgDAAQgBAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgDACIgDADIgEABIgEABQgHAAgDgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABgBAAIgCAEIAAADQAAAFACADQADACAFAAQADAAAEgCQADgBADgDIAAgNIgMAAIgFAAg");
	this.shape_99.setTransform(128.5,20.1);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#FFFFFF").s().p("AAbAXQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgCgDgFAAIgEABIgEACIgDACIgCACIAAACIAAADIAAAdIgCAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgcQAAgGgCgDQgDgDgFAAIgDABIgEABIgDADIgCACIAAAiIgEAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgrIAEAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAEIABgCIAEgCIAEgBIAFgBQAEAAADACQADABABAEIACgCIADgDIAFgBIAGgBQAGAAAEAEQADADAAAJIAAAdg");
	this.shape_100.setTransform(122.6,20);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_101.setTransform(117.8,19.2);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_102.setTransform(115.3,19.5);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#FFFFFF").s().p("AgDAXIgDAAIgEAAIgDgBQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGABIAHABIAFgBIAEgCIACgCIABgEIgBgEIgDgCIgEgBIgEgCIgFgBIgFgCIgDgDIAAgGQAAgFADgDQAEgDAHAAIADAAIACAAIAEAAIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgGAAIgFAAIgDABIgCADIgBADIABADIACADIADACIAFABIAFABIAFABIADAFQABACAAADQABAHgFAEQgEADgHAAIgDgBg");
	this.shape_103.setTransform(111.7,20.1);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FFFFFF").s().p("AgFAWQgEgBgCgDIgEgHIgBgLIABgKIAEgHIAFgEQAEgCADAAQAFAAADACQADABACADIACAGIABAIIAAADIgBACIgbAAIABAIQABADABACQACACADABIAHABIAGAAIAEgBIABABIABAAIAAADIgGABIgHABQgFAAgDgCgAgEgRQgCABgCADIgDAFIAAAHIAXAAIABgBIAAgCIgBgGQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_104.setTransform(107.4,20);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAHAAIAEgBIABABIABAAIAAADIgGABIgIABQgEAAgEgCgAgEgRQgDABgBADIgCAFIgBAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_105.setTransform(100.7,20);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#FFFFFF").s().p("AANAgQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgdQAAgFgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg+IAEAAIABABIAAAXIAGgEQADgCAFAAQAGAAAEAEQAEADAAAIIAAAeg");
	this.shape_106.setTransform(96,19.1);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgHAAIgEAAg");
	this.shape_107.setTransform(92,19.5);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#FFFFFF").s().p("AAAAdIgCgCIgCgEIgBgDIAAggIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAFAAIAAgMIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIAAABIACABIAEAAIACAAIABAAIABABIABABIAAADIgHAAIgEAAg");
	this.shape_108.setTransform(86.8,19.5);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#FFFFFF").s().p("AgNATQgDgDAAgHQAAgIAEgCQAFgDAHAAIAMAAIAAgEIgBgEIgCgEIgEgCIgFAAIgHAAIgFABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAJABIAEACQACACABAEIABAFIAAAfIgEAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgCACIgEADIgEABIgEABQgHAAgEgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAIgDAEIAAADQAAAFADADQADACAEAAQAEAAADgCQAEgBACgDIAAgNIgMAAIgFAAg");
	this.shape_109.setTransform(82.9,20.1);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#FFFFFF").s().p("AgDAXIgEAAIgDAAIgCgBQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGABIAHABIAFgBIAEgCIACgCIAAgEIgBgEIgCgCIgEgBIgEgCIgFgBIgEgCIgEgDIgBgGQAAgFAFgDQADgDAHAAIACAAIAEAAIADAAIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgGgBIgGAAIgEAAIgEABIgCADIAAADIAAADIACADIAEACIAEABIAGABIAEABIADAFQABACABADQgBAHgEAEQgEADgHAAIgDgBg");
	this.shape_110.setTransform(76.6,20.1);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgDgDIgDgHIgBgLIABgKIADgHIAGgEQAEgCADAAQAFAAADACQADABACADIADAGIAAAIIAAADIAAACIgcAAIABAIQABADACACQABACADABIAGABIAIAAIADgBIABABIAAAAIAAADIgFABIgIABQgDAAgFgCgAgEgRQgDABgBADIgDAFIAAAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAIgFgBQgDAAgCABg");
	this.shape_111.setTransform(72.2,20);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#FFFFFF").s().p("AgHAfIgGgBQAAgBgBAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgDIAHABIAHABIAFgBIAEgDIACgDIAAgFIAAgEIgFACQgDACgDAAQgIAAgFgGQgEgFAAgKQABgIABgEQABgFADgCQACgDAEgBIAIgBIAEAAIAEAAIAEABIADAAIABABIAAABIAAACIgCAAIAAAoQAAAIgFAEQgDAEgIAAIgHAAgAgEgZIgFADQgBACgBAEIgBAKQAAAIADAEQADAFAGAAQACgBAEgBIAEgDIAAgfIgDAAIgGAAIgFAAg");
	this.shape_112.setTransform(67.6,20.8);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#FFFFFF").s().p("AgIAfQgEgCgBgDIgDgHIAAgKQgBgMAFgFQAFgGAIAAIAHABIAFACIAAgVIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgDIgGAEQgDACgFAAQgEAAgDgCgAgEgIQgDABgBACQgCACgBADIgBAJQABAKACAEQADAFAGAAIADAAIAEgCIADgCIADgCIAAgdIgGgBIgFgBIgGABg");
	this.shape_113.setTransform(62.7,19.1);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_114.setTransform(59.3,19.2);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_115.setTransform(56.9,20);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#FFFFFF").s().p("AAAAdIgDgCIgBgEIAAgDIAAggIgFAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAACIgLAAIAAAgIAAACIABABIACABIADAAIACAAIABAAIACABIAAABIAAADIgGAAIgFAAg");
	this.shape_116.setTransform(53.6,19.5);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_117.setTransform(50.6,20);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#FFFFFF").s().p("AgNATQgDgDAAgHQAAgIAEgCQAFgDAHAAIAMAAIAAgEIgBgEIgCgEIgEgCIgFAAIgHAAIgFABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAJABIAEACQACACABAEIABAFIAAAfIgEAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgCACIgEADIgEABIgEABQgHAAgEgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAIgDAEIAAADQAAAFADADQADACAEAAQAEAAADgCQAEgBACgDIAAgNIgMAAIgFAAg");
	this.shape_118.setTransform(46.5,20.1);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#FFFFFF").s().p("AgFAWQgDgCgCgDQgCgDgBgFIAAgJQAAgMAEgFQAEgGAIABIADAAIADAAIADABIABAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAACIgFgBIgGAAIgEABQgCABgCACQgCACAAADIgBAJIABAJIACAGQACADACAAIAEABIAHgBIADAAIABAAIAAABIAAADIgFABIgGABQgEAAgEgCg");
	this.shape_119.setTransform(42.4,20.1);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#FFFFFF").s().p("AgDAeQgCgCAAgEIAAg4IAEAAIABABIAAA3IAAAEIADAAIACAAIABABIAAAAIAAACIgCABIgDAAQgCAAgCgCg");
	this.shape_120.setTransform(37.3,19.1);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#FFFFFF").s().p("AgNATQgDgDAAgHQAAgIAEgCQAFgDAHAAIALAAIAAgEIAAgEIgCgEIgEgCIgFAAIgHAAIgFABQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAHgBIAGAAIAJABIAEACQACACABAEIABAFIAAAfIgEAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgEIgCACIgEADIgEABIgDABQgIAAgEgFgAgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABAAAAIgCAEIgBADQAAAFADADQADACAEAAQADAAAEgCQADgBACgDIAAgNIgLAAIgFAAg");
	this.shape_121.setTransform(33.6,20.1);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgIIAAgeIADAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAcQAAAHADACQADADAEAAIAEgBIADgBIAEgCIACgCIAAgjIADAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAArIgEAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIgCACIgEACIgEACIgEAAQgGAAgFgDg");
	this.shape_122.setTransform(29,20.1);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#FFFFFF").s().p("AgIAfQgDgCgDgDIgCgHIAAgKQAAgMAEgFQAFgGAIAAIAHABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgDACgEAAQgGAAgCgCgAgEgIQgDABgBACQgCACAAADIgCAJQAAAKADAEQACAFAHAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgHgBIgFABg");
	this.shape_123.setTransform(24.2,19.1);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_124.setTransform(20.8,19.2);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#FFFFFF").s().p("AAAAXIgCgBIAAgBIgFgKIgFgLIgCgKIgDgMIAEAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQACAKAEAKQADAKAEAIIADgJIAEgJIADgLIACgLIAEAAIABABIAAABIgCALIgEAKIgEALIgFALg");
	this.shape_125.setTransform(17.7,20);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_126.setTransform(14.5,19.2);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#FFFFFF").s().p("AgIAfQgDgCgDgDIgCgHIAAgKQAAgMAEgFQAFgGAIAAIAHABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgDACgEAAQgGAAgCgCgAgEgIQgDABgBACQgCACAAADIgCAJQAAAKADAEQADAFAGAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgGgBIgGABg");
	this.shape_127.setTransform(11.1,19.1);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#FFFFFF").s().p("AANAXQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIACgCIADgCIAFgBIAEgBQAGAAAEAEQAEADAAAJIAAAdg");
	this.shape_128.setTransform(6.4,20);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_129.setTransform(2.9,19.2);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#FFFFFF").s().p("AgGAeIgHgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAgCIAHABIAHAAIAFAAIAEgCIACgEIABgEIAAgGIgGAEQgDABgDAAQgJAAgEgGQgDgGAAgKQAAgGABgFQABgEADgDQADgDADgBIAIgBIAEAAIAEABIAEAAIADABIABAAIABABIAAACIgEAAIAAApQAAAHgDAEQgEAEgIAAIgGgBgAgEgZIgEADQgCACgCAEIgBAJQAAAJAEAFQADADAGAAQACABADgCIAGgDIAAgfIgFgBIgEAAIgGABg");
	this.shape_130.setTransform(178.4,9.5);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#FFFFFF").s().p("AANAXQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIACgCIADgCIAFgBIAEgBQAGAAAEAEQAEADAAAJIAAAdg");
	this.shape_131.setTransform(173.6,8.7);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIACgBIADABIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_132.setTransform(170.1,7.9);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#FFFFFF").s().p("AgDAXIgEAAIgDgBIgCAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIAGABIAHAAIAFAAIAEgCIACgDIAAgDIgBgFIgCgCIgDgBIgFgCIgFgBIgEgCIgDgDIgCgGQABgFAEgEQADgDAHAAIACAAIAEAAIADABIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgGAAIgEAAIgEACIgCACIAAADIAAAEIACACIAEABIAEACIAGACIAEABIADADQABADABAEQgBAGgEAEQgEACgHAAIgDAAg");
	this.shape_133.setTransform(167.1,8.8);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#FFFFFF").s().p("AgMAUQgEgEAAgHQAAgHAFgDQAEgDAHAAIAMAAIAAgDIgBgGIgCgDIgEgBIgFgBIgHABIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAIABIAGAEQACACAAACIABAHIAAAdIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgDACIgDABIgEACIgEAAQgHAAgDgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAIgBADIgBAEQAAAGACACQADACAFAAQADAAAEgCQADgBADgDIAAgNIgMAAIgFAAg");
	this.shape_134.setTransform(162.7,8.8);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#FFFFFF").s().p("AANAgQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgdQAAgFgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg+IAEAAIABABIAAAXIAGgEQADgCAFAAQAGAAAEAEQAEADAAAIIAAAeg");
	this.shape_135.setTransform(158.1,7.8);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#FFFFFF").s().p("AgFAVQgDgBgCgDQgCgDgBgEIgBgKQAAgLAFgGQAFgFAHgBIADAAIADABIACAAIACABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgFgBIgGAAIgEABQgCAAgCADQgCACgBAEIAAAIIAAAKIADAFQACACADABIADABIAHAAIADgBIABABIABAAIAAACIgGACIgGAAQgEAAgEgCg");
	this.shape_136.setTransform(153.9,8.8);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_137.setTransform(150.4,8.7);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgIIAAgeIADAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAcQAAAHADACQADADAEAAIADgBIAFgBIACgCIADgCIAAgjIAEAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAArIgEAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIgDACIgCACIgFACIgEAAQgGAAgFgDg");
	this.shape_138.setTransform(146.2,8.8);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_139.setTransform(141.3,9.5);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#FFFFFF").s().p("AgNASQgEgGAAgMQAAgLAEgGQAEgGAJAAQAKAAAEAGQAEAGAAALQAAAMgEAGQgEAGgKAAQgJAAgEgGgAgFgRQgCABgCACQgCACAAAEIgBAIIABAJQAAAEACACIAEADIAFABIAGgBIAEgDIACgGIABgJIgBgIQAAgEgCgCIgEgDIgGgBIgFABg");
	this.shape_140.setTransform(134.5,8.7);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f("#FFFFFF").s().p("AAAAcIgDgBIgBgDIAAgEIAAgfIgFAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAEIgLAAIAAAeIAAACIABADIACABIADAAIACAAIABAAIACAAIAAABIAAACIgHABIgEgBg");
	this.shape_141.setTransform(130.5,8.2);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f("#FFFFFF").s().p("AgIAfQgEgCgCgDIgCgHIAAgKQgBgMAFgFQAFgGAIAAIAHABIAEACIAAgVIAEAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAAA/IgEAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgDIgFAEQgDACgEAAQgGAAgCgCgAgEgIQgDABgBACQgCACgBADIgBAJQAAAKADAEQADAFAGAAIADAAIAEgCIADgCIACgCIAAgdIgEgBIgGgBIgGABg");
	this.shape_142.setTransform(124.4,7.8);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f("#FFFFFF").s().p("AgGAWQgDgBgCgDIgEgHIgBgLIABgKIAEgHIAFgEQADgCAEAAQAFAAADACQAEABABADIADAGIAAAIIAAADIAAACIgcAAIABAIQAAADACACQACACADABIAGABIAHAAIAEgBIABABIABAAIAAADIgGABIgIABQgDAAgFgCgAgEgRQgCABgCADIgCAFIgBAHIAXAAIAAgBIAAgCIAAgGQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBQgDAAgCABg");
	this.shape_143.setTransform(119.8,8.7);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.f("#FFFFFF").s().p("AgIAXQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgrIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFIADgCIACgCIAEgCIAEgBIACABIABABIAAADIgCAAIgBAAQgEAAgDACIgGAFIAAAhg");
	this.shape_144.setTransform(116,8.7);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgHQAAgHAEgDQAFgDAHAAIALAAIAAgDIAAgGIgCgDIgEgBIgFgBIgHABIgFAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAJABIAEAEQACACABACIABAHIAAAdIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgCACIgEABIgEACIgDAAQgIAAgEgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAAAIgCADIgBAEQAAAGADACQADACAEAAQADAAAEgCQADgBACgDIAAgNIgLAAIgFAAg");
	this.shape_145.setTransform(111.9,8.8);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_146.setTransform(107.2,9.5);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.f("#FFFFFF").s().p("AAbAXQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgCgDgEAAIgFABIgEACIgDACIgCACIAAACIAAADIAAAdIgCAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgFABIgDABIgDADIgDACIAAAiIgDAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAEIACgCIAEgCIAEgBIAFgBQAEAAADACQADABABAEIACgCIAEgDIAEgBIAGgBQAGAAAEAEQADADAAAJIAAAdg");
	this.shape_147.setTransform(101.2,8.7);

	this.shape_148 = new cjs.Shape();
	this.shape_148.graphics.f("#FFFFFF").s().p("AgNASQgEgGAAgMQAAgLAEgGQAEgGAJAAQAKAAAEAGQAEAGAAALQAAAMgEAGQgEAGgKAAQgJAAgEgGgAgFgRQgCABgCACQgCACAAAEIgBAIIABAJQAAAEACACIAEADIAFABIAGgBIAEgDIACgGIABgJIgBgIQAAgEgCgCQgCgCgCgBIgGgBIgFABg");
	this.shape_148.setTransform(95,8.7);

	this.shape_149 = new cjs.Shape();
	this.shape_149.graphics.f("#FFFFFF").s().p("AgFAVQgDgBgCgDQgCgDgBgEIgBgKQABgLAEgGQAFgFAHgBIADAAIADABIACAAIACABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgFgBIgGAAIgEABQgCAAgCADQgCACAAAEIgBAIIABAKIACAFQACACADABIADABIAHAAIADgBIABABIAAAAIAAACIgFACIgGAAQgEAAgEgCg");
	this.shape_149.setTransform(90.8,8.8);

	this.shape_150 = new cjs.Shape();
	this.shape_150.graphics.f("#FFFFFF").s().p("AgDAXIgEAAIgDgBIgDAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIAGABIAHAAIAFAAIAEgCIACgDIAAgDIAAgFIgDgCIgEgBIgEgCIgFgBIgEgCIgEgDIgBgGQAAgFAFgEQADgDAHAAIACAAIAEAAIADABIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgGAAIgFAAIgDACIgCACIAAADIAAAEIACACIADABIAFACIAGACIAEABIADADQACADAAAEQAAAGgFAEQgEACgHAAIgDAAg");
	this.shape_150.setTransform(84.6,8.8);

	this.shape_151 = new cjs.Shape();
	this.shape_151.graphics.f("#FFFFFF").s().p("AgHAeIgGgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAgCIAHABIAHAAIAFAAIAEgCIACgEIAAgEIAAgGIgFAEQgDABgDAAQgIAAgFgGQgEgGAAgKQABgGABgFQABgEADgDQACgDAEgBIAIgBIAEAAIAEABIAEAAIADABIABAAIAAABIAAACIgCAAIAAApQAAAHgFAEQgDAEgIAAIgHgBgAgEgZIgFADQgBACgBAEIgBAJQAAAJADAFQADADAGAAQACABAEgCIAEgDIAAgfIgDgBIgGAAIgFABg");
	this.shape_151.setTransform(80.2,9.5);

	this.shape_152 = new cjs.Shape();
	this.shape_152.graphics.f("#FFFFFF").s().p("AANAXQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgcQAAgGgDgDQgDgDgEAAIgEABIgEABIgDADIgCACIAAAiIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgrIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAEIACgCIADgCIAFgBIAEgBQAGAAAEAEQAEADAAAJIAAAdg");
	this.shape_152.setTransform(75.3,8.7);

	this.shape_153 = new cjs.Shape();
	this.shape_153.graphics.f("#FFFFFF").s().p("AAAAfQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIACgBIADABIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_153.setTransform(71.9,7.9);

	this.shape_154 = new cjs.Shape();
	this.shape_154.graphics.f("#FFFFFF").s().p("AAAAXIgCgBIAAgBIgFgKIgFgLIgCgKIgDgMIAFAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQACAKAEAKQADAKADAIIAFgJIADgJIADgLIACgLIAEAAIABABIAAABIgCALIgDAKIgFALIgFALg");
	this.shape_154.setTransform(68.8,8.7);

	this.shape_155 = new cjs.Shape();
	this.shape_155.graphics.f("#FFFFFF").s().p("AgNAUQgDgEAAgHQAAgHAFgDQAEgDAHAAIALAAIAAgDIAAgGIgCgDIgEgBIgFgBIgHABIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAJABIAEAEQADACAAACIABAHIAAAdIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgCACIgEABIgEACIgDAAQgIAAgEgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAAAIgCADIgBAEQAAAGADACQADACAEAAQAEAAADgCQADgBACgDIAAgNIgLAAIgFAAg");
	this.shape_155.setTransform(64.3,8.8);

	this.shape_156 = new cjs.Shape();
	this.shape_156.graphics.f("#FFFFFF").s().p("AgDAXIgDAAIgEgBIgDAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgCIAGABIAHAAIAFAAIAEgCIACgDIABgDIgBgFIgDgCIgEgBIgEgCIgFgBIgFgCIgDgDIAAgGQgBgFAEgEQAEgDAHAAIACAAIADAAIAEABIADABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgGAAIgFAAIgDACIgCACIAAADIAAAEIACACIADABIAFACIAFACIAFABIADADQABADAAAEQABAGgFAEQgEACgHAAIgDAAg");
	this.shape_156.setTransform(60.1,8.8);

	this.shape_157 = new cjs.Shape();
	this.shape_157.graphics.f("#FFFFFF").s().p("AAMAgIgCgBIgJgKIgMgLIAAAWIgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg+IAEAAIABABIAAAkQAHgEAFgEIAJgKIADAAIABABIAAABIgBABIgDAEIgFAEIgFAEIgGAFIAHAGIAGAGIAFAGIAFAGg");
	this.shape_157.setTransform(53.9,7.8);

	this.shape_158 = new cjs.Shape();
	this.shape_158.graphics.f("#FFFFFF").s().p("AgEAVQgEgBgCgDQgCgDAAgEIgBgKQgBgLAFgGQAEgFAIgBIADAAIADABIACAAIACABQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAADIgGgBIgEAAIgFABQgDAAgBADQgCACgBAEIgBAIIABAKIADAFQACACACABIAFABIAFAAIAEgBIABABIABAAIAAACIgGACIgGAAQgEAAgDgCg");
	this.shape_158.setTransform(49.7,8.8);

	this.shape_159 = new cjs.Shape();
	this.shape_159.graphics.f("#FFFFFF").s().p("AgMAUQgEgEAAgHQAAgHAFgDQAEgDAHAAIAMAAIAAgDIgBgGIgCgDIgEgBIgFgBIgHABIgEAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIAAgDIAHgBIAGgBIAIABIAGAEQACACAAACIABAHIAAAdIgDAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIgDACIgDABIgEACIgEAAQgHAAgDgDgAgFAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBAAIgCADIAAAEQAAAGACACQADACAFAAQADAAAEgCQADgBADgDIAAgNIgMAAIgFAAg");
	this.shape_159.setTransform(45.3,8.8);

	this.shape_160 = new cjs.Shape();
	this.shape_160.graphics.f("#FFFFFF").s().p("AgNAfQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgCIAEgBIAEAAIAFAAIAEgBIAIABIAHAEQACADACAEIABALIgBAJQgBAFgCADIgFAEQgEACgFAAIgGgBIgFgCIAAASgAgKgZIAAAiIAFACIAFAAIAGAAQADgBABgDQACgCABgDIABgJIgBgIQgBgEgCgCIgFgDIgHgBIgDAAIgFAAg");
	this.shape_160.setTransform(40.6,9.5);

	this.shape_161 = new cjs.Shape();
	this.shape_161.graphics.f("#FFFFFF").s().p("AgLACIgBgBIAAgCIAYAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAACg");
	this.shape_161.setTransform(36.4,8.5);

	this.shape_162 = new cjs.Shape();
	this.shape_162.graphics.f("#FFFFFF").s().p("AAAAfQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgrIACAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAArgAgCgXQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIABgDIACgBIADABIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgDABIgCgBg");
	this.shape_162.setTransform(33.6,7.9);

	this.shape_163 = new cjs.Shape();
	this.shape_163.graphics.f("#FFFFFF").s().p("AAAAcIgDgBIgBgDIAAgEIAAgfIgFAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgDIAGAAIAAgMIADAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAKIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAEIgLAAIAAAeIAAACIABADIACABIADAAIACAAIABAAIACAAIAAABIAAACIgGABIgFgBg");
	this.shape_163.setTransform(31.1,8.2);

	this.shape_164 = new cjs.Shape();
	this.shape_164.graphics.f("#FFFFFF").s().p("AgDAeQgCgCAAgEIAAg3IAEAAIABABIAAA2IAAADIADABIACAAIABAAIAAABIAAADIgCAAIgDABQgCgBgCgCg");
	this.shape_164.setTransform(28.5,7.8);

	this.shape_165 = new cjs.Shape();
	this.shape_165.graphics.f("#FFFFFF").s().p("AgMAUQgEgEAAgIIAAgeIAEAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAcQAAAHADACQACADAFAAIADgBIAFgBIACgCIADgCIAAgjIAEAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAArIgDAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIgDACIgCACIgFACIgEAAQgGAAgEgDg");
	this.shape_165.setTransform(24.8,8.8);

	this.shape_166 = new cjs.Shape();
	this.shape_166.graphics.f("#FFFFFF").s().p("AAVAfQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgNIAAgNIAAgMIgBgNIgPAkIgEAAIgBAAIgBgBIgOgjIAAANIgBANIAAANIgBANIgEAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIABgeIABgeIAFAAIABABIAQAnIASgoIADAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIACAeIABAeg");
	this.shape_166.setTransform(19.2,7.9);

	this.shape_167 = new cjs.Shape();
	this.shape_167.graphics.f("#FFFFFF").s().p("AgJANIAAgCIABgBIAHgIIgNgDIABgDIABgBIACABIAKADIgBgMIACAAIABABIAAABIAAAKIAMgEIABADIAAABIgCABIgKACIAIAKIgDACIgBAAIgBgBIgGgJIgGALg");
	this.shape_167.setTransform(14.1,6.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_167},{t:this.shape_166},{t:this.shape_165},{t:this.shape_164},{t:this.shape_163},{t:this.shape_162},{t:this.shape_161},{t:this.shape_160},{t:this.shape_159},{t:this.shape_158},{t:this.shape_157},{t:this.shape_156},{t:this.shape_155},{t:this.shape_154},{t:this.shape_153},{t:this.shape_152},{t:this.shape_151},{t:this.shape_150},{t:this.shape_149},{t:this.shape_148},{t:this.shape_147},{t:this.shape_146},{t:this.shape_145},{t:this.shape_144},{t:this.shape_143},{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text3, new cjs.Rectangle(0,0,193.2,26.6), null);


(lib.text2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAUIgCgCIABgDIAMgMIgUgEIADgIIACgCIACAAIAPAHIgBgUIAIAAIACABIAAADIgBAQIASgIIADAJQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgQADIANAPIgHAFQAAABgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAIgCgCIgIgPIgKASg");
	this.shape.setTransform(203.1,9.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAoIgGgBIgGgBIgFgBIgCgCIgBgDIAAgGIALABIAMAAQAIAAAEgCQADgDAAgFIAAgEIgDgDIgFgDIgHgCIgJgDQgFgBgDgCIgFgGQgBgDAAgGQAAgMAHgGQAHgFAMAAIAFAAIAGABIAFABIAEABIADACIAAADIAAAGIgLgBIgKAAQgHAAgDACQgEACAAAFIABAEQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAIAFADIAHACIAJACQAEACADABQAEACABAEQACAEAAAGQAAAHgCAEQgCAFgEADQgDADgGABIgKABIgGAAg");
	this.shape_1.setTransform(197.3,13.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARA2IgDgBIgCgDIgFgIIgGgIIgHgIIgJgIIAAAkIgMAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAhnIALAAIADABIABADIAAA6QAKgIAGgIIAMgPIALAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIgCAEIgEAFIgGAIIgIAHIgJAIIAKAJIAIAKIAIAKIAHAMg");
	this.shape_2.setTransform(191.1,11.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgIAlQgGgCgDgFQgEgFgCgIQgBgHAAgKQAAgUAHgJQAHgKAPAAIAKABIAHACIACACIABADIAAAGIgJgBIgIAAIgIABQgDABgCADQgCAEgBAFIgBAMQAAAIABAFQABAGADADQACADACABIAIABIAIAAIAGgBQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIAAAGIgIADIgMABQgHAAgGgDg");
	this.shape_3.setTransform(184.5,13.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXAhQgGgGAAgMQAAgHACgEQACgEAFgDQAEgDAFgBIALgBIAPAAIAAgFQAAgIgEgDQgEgCgJAAIgLAAIgHABIgEgBIAAgDIAAgGIAMgDIAMgBQAIAAAHACQAFACAEADQADAEABAFQACAFAAAGIAAAyIgKAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBgBIAAgCIgBgFQgEAEgFADQgGADgHAAQgMAAgFgHgAgIADQgDABgBACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAgBABIAAAFQAAAHADADQADADAHAAQAFAAAEgCIAIgGIAAgSIgPAAIgIABg");
	this.shape_4.setTransform(177.9,13.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAzQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgyIAAgRIABgSIgDAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAgIIAFgBIAIAAIAIgBIAIAAQAJAAAHABQAHADAEAEQAFAFACAHQACAHAAALQAAAUgHAJQgHAKgOAAQgGAAgEgCIgHgDIAAAdgAgMgmIAAAyQADACADAAIAHABIAHgBQAEgCACgCIADgJIABgNIgBgMIgDgIQgDgDgEgCQgEgBgGgBIgEAAIgFABg");
	this.shape_5.setTransform(170.8,14.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSAHQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAgJIAoAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIAAAJg");
	this.shape_6.setTransform(164.5,12.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgDA1QgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhIIALAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABIgAgGgkQgCgCAAgFQAAgEACgDQACgCAEAAQAFAAACACQACADAAAEQAAAFgCACQgCABgFAAQgEAAgCgBg");
	this.shape_7.setTransform(160.5,11.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgGAsQgFgFAAgKIAAgtIgFAAQgEAAAAgEIAAgIIAJAAIABgUIAKAAQAAAAABAAQAAABABAAQAAABABAAQAAABAAABIAAAQIAPAAIACABIABACIAAAJIgSAAIAAAsQAAAEABACQACACAEAAIAEAAIADAAQAEAAAAAEIAAAHIgGABIgHABQgKAAgEgFg");
	this.shape_8.setTransform(156.6,12.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgEA1QgDgCgCgDQgCgCAAgFIgBgKIAAhUIALAAIACAAIACADIAABWQAAAEABABIAEABIAEABIABADIAAAHIgFABIgFAAQgEAAgDgBg");
	this.shape_9.setTransform(152.8,11.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRAmQgEgCgDgEIgEgIIgBgLIAAgzIALAAIADABIABADIAAAuQAAAIADADQADAEAHAAQAFAAAEgDIAHgFIAAg5IAMAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABIIgJAAIgDgBIgBgDIgBgFQgJAKgOAAQgGAAgEgBg");
	this.shape_10.setTransform(147.2,13.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAoAnQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAgtQAAgJgEgDQgDgDgGgBQgGAAgEADIgHAGIAAAIIAAAwIgKAAIgCgBIgBgDIAAgtQAAgJgEgDQgDgDgGgBQgFABgFACIgGAFIAAA5IgMAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAhHIAJAAIACAAIACADIAAAFIAKgIQAFgCAJAAQAFAAAGACQAEADADAGQAEgEAFgEQAHgDAJAAQAKAAAGAGQAFAGAAAOIAAAzg");
	this.shape_11.setTransform(137.7,13.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgPAnQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhIIAJAAIADABIACADIAAAHQADgFAFgDQAGgEAGAAIAEABIABAEIAAAKIgCgBIgCAAQgHAAgEACQgFACgDAFIAAA2g");
	this.shape_12.setTransform(127.3,13.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgKAmQgHgCgEgFQgEgFgCgHQgCgIAAgLQAAgKACgHQACgIAEgFQAEgFAGgCQAGgCAGAAQAJAAAGADQAFACADAEQAEAEABAGIABAMIgBAIIgBAGIgqAAIABAKQABAEACADQADACAEACIAKABIALgBIAGAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAAGIgKADIgPABQgHAAgGgCgAgFgaQgEACgCADIgDAHIAAAKIAeAAIAAgCIAAgCQAAgKgDgFQgDgEgIAAQgEAAgDABg");
	this.shape_13.setTransform(121.1,13.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AATAnIgDgBIgBgDIAAgtQAAgJgDgDQgDgDgHgBQgFABgEACIgHAGIAAA4IgMAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhHIAJAAIADAAIABADIABAFQAJgKAOAAQAMAAAFAHQAFAIAAALIAAAzg");
	this.shape_14.setTransform(114,13.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgYAeQgHgKAAgUQAAgUAHgJQAIgKAQAAQARAAAIAKQAHAJAAAUQAAAUgHAKQgIAKgRAAQgQAAgIgKgAgHgaQgDABgCAEIgDAIIgBANIABAOQABAFACADQACADADABQADACAEAAQAFAAADgCQADgBACgDQACgDABgFIABgOIgBgNIgDgIIgFgFQgDgBgFgBQgEABgDABg");
	this.shape_15.setTransform(106.6,13.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgEA0QAAAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhWIgYAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgKIBCAAIADABIABACIAAAKIgcAAIAABag");
	this.shape_16.setTransform(99.2,11.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcA1QgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhhIAPgDIAQgBQARABAIAHQAJAIAAASQAAAKgCAGQgDAGgEAEQgEADgGADQgGACgIAAIgHgBIgJgBIAAAngAgQgmIAAAnIAIABIAHABIAIgBQADgBADgBQACgCABgFIABgLIgBgKQgBgFgDgCQgCgDgEAAIgHgBIgJAAIgGABg");
	this.shape_17.setTransform(89.3,11.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAXA0IgCgBIgBgDIAAgrIgnAAIAAAvIgLAAQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhjIAMAAIADABIAAACIAAApIAnAAIAAgsIAMAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABkg");
	this.shape_18.setTransform(80.9,11.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgEA1QgDgCgCgDQgCgCAAgFIgBgKIAAhUIALAAIACAAIABADIAABWQAAAEACABIAEABIAEABIABADIAAAHIgFABIgFAAQgEAAgDgBg");
	this.shape_19.setTransform(72.6,11.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgXAhQgGgGAAgMQAAgHACgEQADgEADgDQAEgDAGgBIALgBIAPAAIAAgFQAAgIgEgDQgEgCgJAAIgLAAIgIABIgCgBIgBgDIAAgGIALgDIANgBQAJAAAFACQAGACADADQAEAEACAFQABAFAAAGIAAAyIgJAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBgBIgBgCIAAgFQgEAEgGADQgFADgHAAQgLAAgGgHgAgHADQgEABgBACQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIgBAFQAAAHADADQADADAHAAQAFAAAEgCIAIgGIAAgSIgPAAIgHABg");
	this.shape_20.setTransform(67.1,13.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AATAnIgDgBIgBgDIAAgtQAAgJgDgDQgDgDgHgBQgFABgEACIgHAGIAAA4IgMAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhHIAJAAIADAAIABADIABAFQAJgKAOAAQAMAAAFAHQAFAIAAALIAAAzg");
	this.shape_21.setTransform(60,13.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgDA1QgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhIIALAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABIgAgGgkQgCgCAAgFQAAgEACgDQACgCAEAAQAFAAACACQACADAAAEQAAAFgCACQgCABgFAAQgEAAgCgBg");
	this.shape_22.setTransform(54.9,11.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHA0IgGAAIgFgBIgGgCIgBgCIgBgDIAAgGIAKABIAKABQAKAAAFgDQAEgDAAgIIAAgJIgJAEQgEACgGAAQgHAAgFgDQgFgCgDgFQgDgFgCgHIgBgNQAAgLADgIQABgIAFgEQAEgFAIgBQAHgCAHAAIANAAIALACIAEACIACADIAAAHIgGAAIAAASIABATIAAAZQAAAOgIAGQgHAHgOAAIgGAAgAgFgmQgEABgCADQgDADgCAFIgBAOIABALIADAHQACADADABIAHABQAEAAAEgBIAGgDIAAgtIgFgBIgFAAIgIABg");
	this.shape_23.setTransform(49.9,14.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgDA1QgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhIIALAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABIgAgGgkQgCgCAAgFQAAgEACgDQACgCAEAAQAFAAACACQACADAAAEQAAAFgCACQgCABgFAAQgEAAgCgBg");
	this.shape_24.setTransform(44.7,11.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgPAnQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhIIAKAAIACABIACADIAAAHQADgFAFgDQAFgEAHAAIAEABIABAEIAAAKIgCgBIgCAAQgGAAgGACQgEACgEAFIAAA2g");
	this.shape_25.setTransform(41.2,13.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgPAzQgGgCgFgGQgFgGgDgKQgDgKABgRQgBgQADgKQADgLAFgGQAFgFAGgDQAIgCAHAAQAIAAAIACQAGADAFAFQAFAGADALQADAKgBAQQABARgDAKQgDAKgFAGQgFAGgGACQgIADgIAAQgHAAgIgDgAgJgmQgFACgCAFQgDAFAAAIIgBASIABATQAAAIADAFQACAEAFACQAEACAFAAQAGAAAEgCQAEgCADgEQADgFAAgIIABgTIgBgSQAAgIgDgFQgDgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_26.setTransform(34.2,11.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AATA2IgDgBIgBgDIAAgvQAAgHgDgDQgDgEgHAAQgFAAgEADIgHAFIAAA5IgMAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAhnIALAAIADABIABADIAAAjQAEgFAGgCQAFgCAHAAQAMAAAFAHQAFAHAAALIAAA0g");
	this.shape_27.setTransform(23.6,11.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgGAsQgFgFAAgKIAAgtIgFAAQgEAAAAgEIAAgIIAJAAIABgUIAKAAQAAAAABAAQAAABABAAQAAABABAAQAAABAAABIAAAQIAPAAIACABIABACIAAAJIgSAAIAAAsQAAAEABACQACACAEAAIAEAAIADAAQAEAAAAAEIAAAHIgGABIgHABQgKAAgEgFg");
	this.shape_28.setTransform(17.5,12.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgDA1QgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhIIALAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABIgAgGgkQgCgCAAgFQAAgEACgDQACgCAEAAQAFAAACACQACADAAAEQAAAFgCACQgCABgFAAQgEAAgCgBg");
	this.shape_29.setTransform(13.7,11.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AARAmIgCgBIgBgCIgOgwIgNAzIgMAAIgCgBIgCgCIgGgSIgFgRIgEgTIgCgSIAMAAQAAAAABAAQABAAAAABQABAAAAABQAAAAAAABIACAOIACAOIADAOIAEAOIAPg1IAIAAIADABIACADIAOAxIADgOIAEgPIACgQIACgOIALAAIADABIAAADIAAADIgBAFIgGAfQgFAQgGAQg");
	this.shape_30.setTransform(7.2,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text2, new cjs.Rectangle(0,0,207.9,23.8), null);


(lib.text1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAxBwQgIgDgHgHQgGgIgEgLQgDgMAAgSQAAgRADgMQAEgMAGgHQAHgGAIgDQAJgDALAAQAKAAAJADQAJADAGAGQAGAHAEAMQAEAMAAARQAAASgEAMQgEALgGAIQgGAHgJADQgJADgKAAQgLAAgJgDgAAzAWQgEAKAAAVQAAAWAEAJQAGAKAMAAQAMAAAFgKQAFgJAAgWQAAgVgFgKQgFgJgMAAQgMAAgGAJgAhHBwQgGAAAAgGIABgEICBjVIATAAQAFAAAAAGIgBAFIiADUgAhXAFQgJgDgGgGQgHgIgDgLQgEgMABgSQgBgRAEgMQADgLAHgIQAGgHAJgDQAJgDAKAAQAKAAAJADQAJADAGAHQAHAIADALQAEAMAAARQAAASgEAMQgDALgHAIQgGAGgJADQgJADgKAAQgKAAgJgDgAhVhUQgFAKAAAVQAAAWAFAJQAFAKAMAAQANAAAEgKQAFgJgBgWQABgVgFgKQgEgJgNAAQgMAAgFAJg");
	this.shape.setTransform(192.7,23.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeBvQgNgFgKgNQgKgMgFgXQgFgXAAgjQAAgiAFgWQAFgXAKgNQAKgNANgFQAOgFAQAAQARAAAOAFQAOAFAJANQAKAMAFAWQAFAYAAAiQAAAjgFAXQgFAXgKAMQgJANgOAFQgOAFgRAAQgQAAgOgFgAgThSQgIAEgEAKQgEALgCAQQgCARAAAYQAAAYACASQACAQAEALQAEAKAIAEQAIAFALAAQAMAAAIgFQAIgEAEgKQAFgLABgQQACgSAAgYQAAgYgCgRQgBgQgFgLQgEgKgIgEQgIgFgMAAQgLAAgIAFg");
	this.shape_1.setTransform(171.4,23.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARByQgIAAAAgHIAAi3IglAOIgFACIgDAAQgGAAAAgGIAAgTIAPgHQAbgMAOgFQAPgEAGAAQAEAAACACQACACAAADIAADcg");
	this.shape_2.setTransform(152.4,23.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag1BDQgRgWAAgtQAAgtARgVQARgVAkAAQAlAAARAVQARAVAAAtQAAAtgRAWQgRAVglAAQgkAAgRgVgAgQg6QgHADgEAHQgFAHgCAMQgCAMAAARQAAASACAMQACAMAFAHQAEAHAHADQAHADAJAAQAKAAAHgDQAHgDAEgHQAFgHACgMQACgMAAgSQAAgRgCgMQgCgMgFgHQgEgHgHgDQgHgDgKAAQgJAAgHADg");
	this.shape_3.setTransform(131.1,26.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPBhQgLgLAAgXIAAhjIgMAAQgIAAAAgIIAAgTIAVAAIABgrIAXAAQAHAAAAAHIAAAkIAhAAQADAAACACQADACAAAEIAAATIgpAAIAABiQAAAJADAFQADAFAJAAIAKgBIAHAAQAJAAAAAIIAAAPIgPADIgOABQgXAAgKgKg");
	this.shape_4.setTransform(117.1,24.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1BxQgIAAAAgHIAAhuIAAgnIABgoIgFAAQgHAAAAgHIAAgQIAMgCIAQgCIASgBIATgBQAUAAAPAEQAQAEAJAKQAKAKAFAQQAFARAAAYQAAAsgQAVQgPAVggAAQgNAAgJgDIgQgHIAABAgAgchVIAABvQAHADAHACQAHACAIAAQAKAAAHgDQAHgCAFgHQAFgHACgMQACgLAAgSQAAgQgCgLQgCgLgFgIQgGgHgJgDQgJgDgNAAIgKAAIgLABg");
	this.shape_5.setTransform(96.9,29.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnBSQgJgEgGgIQgGgHgDgLQgDgLAAgNIAAhxIAaAAQADAAACACQADACAAAEIAABnQAAARAHAHQAHAIAOAAQAMAAAKgGQAKgFAFgGIAAh+IAaAAQAIAAAAAIIAACfIgVAAQgDAAgDgBQgCgCgBgFIgBgKQgVAWgfAAQgNAAgKgEg");
	this.shape_6.setTransform(80.3,26.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZBTQgNgEgJgLQgJgKgFgRQgEgRAAgXQAAgXAEgRQAFgRAJgKQAIgLANgFQANgFAQAAQAUAAALAGQANAFAGAJQAIAKACAMQADAMAAAPIgBASQgBAIgCAFIhfAAQAAANADAJQACAJAGAGQAFAGAJACQAIADAPAAQANAAALgBIAOgCQAHAAABAIIAAAOQgJADgNACQgOADgSAAQgSAAgOgFgAgNg6QgIAEgEAGQgEAHgCAKQgCAJAAAMIBEAAIABgFIAAgEQAAgVgGgLQgHgLgTAAQgKAAgHAEg");
	this.shape_7.setTransform(57.9,26.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgJBUQgFAAgCgCIgDgGQgSgmgNgoQgNgogFgpIAbAAQAHAAABAHIAFAiIAIAiQAFAQAGARIAKAfIAMghQAGgRAEgSIAJglIAFgiIAZAAQAHAAAAAHIgBAIIgBAKQgHAkgMAiQgNAlgRAjg");
	this.shape_8.setTransform(42.2,26.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag0BJQgNgOAAgZQAAgQAFgKQAFgJAJgGQAIgGAMgDQAMgCAOAAIAhAAIAAgMQAAgRgJgGQgJgGgUAAQgPAAgLABIgQACQgEAAgCgCQgCgDAAgDIAAgOQAMgEAPgCQAOgCAOAAQATAAANAEQAMAEAIAHQAHAIAEALQADALAAANIAABwIgVAAQgFAAgBgCIgCgGIgCgKQgIAIgMAHQgMAGgRAAQgaAAgMgOgAgSAGQgGACgEAEQgEAEgBAFQgCAGAAAGQAAAPAIAHQAHAHAPAAQAMAAAJgFQAKgFAHgHIAAgpIgiAAQgKAAgHACg");
	this.shape_9.setTransform(26.4,26.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjB0QgPgCgIgDQgFgCgBgDQgCgCAAgEIAAgRIAaAEQAOABAQAAQAMAAAJgCQAJgDAGgEQAFgFACgGQACgHAAgIQAAgJgCgGQgDgGgFgEIgOgIIgVgIQgOgFgKgGQgLgEgHgHQgIgIgEgKQgEgKAAgQQAAgfASgQQASgQAkAAQAOAAAOACQAOACAHADQAFACACADIABAGIAAAPIgZgCQgNgCgOAAQgMAAgIACQgJADgFAEQgFADgCAGQgCAGAAAIQAAAJACAGQACAGAGAEQAFAEAJAEIAVAIIAXAKQALAFAIAGQAIAIAEAKQAEALAAARQAAAjgTAPQgTAQgjAAQgQAAgPgCg");
	this.shape_10.setTransform(10.5,23.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.text1, new cjs.Rectangle(0,0,207.3,47.5), null);


(lib.product_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.product();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.product_1, new cjs.Rectangle(0,0,300,250), null);


(lib.logoHP = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSKEICClqIC2AAQAXAAAXgQQAXgQAIgXICPmGQARgxgXghQgYgjg0AAIj7AAIlJOLQjXg0iLitQiNiwAAjiQAAjbCFitQCDipDOg6IlIOFICIAAICvneIBmAAIiuHeICIAAICim9QARgxgYghQgYgjgyAAIhzAAICElqIAcgBQELAAC8C8QC9C9AAEKQAAEKi9C+Qi8C8kLAAgACQDFICPmJIBnAAIiQGJg");
	this.shape.setTransform(64.4,64.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoHP, new cjs.Rectangle(0,0,128.8,128.8), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAQApIgEgBIgCgDIgKgpIgJAtIgUAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgCgDQgGgTgDgTQgEgTgCgUIAVAAQAGAAAAAFIABAMIABANIABAOIACANIALgyIAOAAQAAAAABAAQABAAAAAAQABABAAAAQAAAAABABIACADIAKAtIACgOIABgPIABgQIABgMIAUAAQAAAAABAAQABAAAAAAQABAAAAAAQAAABABAAIABAFIAAADIgBAFIgFAfQgDARgHATg");
	this.shape.setTransform(77.2,14.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPApQgIgDgEgFQgEgFgCgIQgCgIAAgMQAAgLACgIQACgIAEgFQAEgFAIgDQAHgCAIAAQAKAAAHACQAHADAEAFQAEAFADAIQACAIAAALQAAAMgCAIQgDAIgEAFQgEAFgHADQgHACgKAAQgIAAgHgCgAgEgWQAAABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAHIAAALIAAANIACAHQAAAAAAABQAAAAABABQAAAAABAAQAAABAAAAIAEABIAEgBQABAAAAgBQABAAAAAAQABgBAAAAQAAgBABAAIABgHIABgNIgBgLIgBgHQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBIgEAAIgEAAg");
	this.shape_1.setTransform(67.3,14.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAOAqQgGAAAAgFIAAgwQAAgDgBgDQgCgCgEAAIgEABIgEADIAAA5IgVAAQgGAAAAgFIAAhMIAPAAIAFABIADAFIABADQAFgGAFgDQAFgCAHAAQAXAAAAAcIAAA3g");
	this.shape_2.setTransform(58.6,14.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA3QgGAAAAgFIAAgyIABgQIABgRIgDAAQgEABAAgGIAAgNIAFgBIAIgBIALgBIALAAQAKAAAIACQAIACAFAEQAFAFACAIQACAIAAALQAAANgCAIQgCAIgEAFQgDAFgFACQgFADgGgBQgGABgDgCIgHgEIAAAfgAgFAIQADABADABIAFgBIADgEIACgGIAAgNIAAgJIgCgGQgBgDgDgBQgCgBgDgBIgDABIgCAAg");
	this.shape_3.setTransform(46.8,16.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQApQgGgDgFgFQgFgFgCgIQgCgIAAgMQAAgLACgIQACgIAFgFQAFgFAGgDQAIgCAIAAQAKAAAHACQAGADAFAFQAFAFACAIQABAIAAALQAAAMgBAIQgCAIgFAFQgFAFgGADQgHACgKAAQgIAAgIgCgAgDgWQgBABAAAAQgBAAAAABQgBAAAAABQAAAAgBABIgBAHIgBALIABANIABAHQABAAAAABQAAAAABABQAAAAABAAQAAABABAAIADABIAFgBQAAAAAAgBQABAAAAAAQABgBAAAAQAAgBABAAIABgHIAAgNIAAgLIgBgHQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAgBIgFAAIgDAAg");
	this.shape_4.setTransform(38.3,14.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAOA5QgGAAAAgFIAAgxQAAgDgBgCQgCgCgEAAIgEABIgEADIAAA5IgVAAQgGAAAAgFIAAhtIAVAAQAGAAAAAGIAAAiQAHgJAMAAQAXAAAAAbIAAA4g");
	this.shape_5.setTransform(29.7,13.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQA4QgIAAgDgCQgDgBgCgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgMIAMAAIANABIAIgBIAEgCIADgDIAAgEIAAgFIgDgDIgFgEIgIgDQgIgDgFgEQgEgCgDgDIgEgJIgBgMQAAgJACgGQADgHAFgEQAFgEAHgBQAIgCAHAAIAOABIAIACQAFACAAACIABAFIAAALIgHAAIgFgBIgGAAIgGAAIgHABIgEABIgCAEIgBADIABAFIABADIAFACIAJAFIAMAGQAFADADADQADAEABAEQACAGAAAHQAAAJgDAGQgCAHgEAEQgEAFgIABQgHACgKAAIgNgBg");
	this.shape_6.setTransform(21.3,13.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0096D6").s().p("AnzCHIAAkNIPnAAIAAENg");
	this.shape_7.setTransform(50,13.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(0,0,100,27), null);


(lib.blueBall = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0096D6").s().p("A1GVGQovovAAsXQAAsWIvowQIwovMWAAQMXAAIvIvQIwIwAAMWQAAMXowIvQovIwsXAAQsWAAowowg");
	this.shape.setTransform(191,191);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blueBall, new cjs.Rectangle(0,0,382,382), null);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_119 = function() {
		if (!this.looped) this.looped = 1;    
		if (this.looped++ > 2) this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(119).call(this.frame_119).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(120));

	// logoHP
	this.instance = new lib.logoHP();
	this.instance.parent = this;
	this.instance.setTransform(36.2,45,0.388,0.388,0,0,0,64.7,64.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(120));

	// cta
	this.instance_1 = new lib.cta();
	this.instance_1.parent = this;
	this.instance_1.setTransform(655,115,1.2,1.2,0,0,0,50,13.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(21).to({_off:false},0).to({y:45,alpha:1},12,cjs.Ease.quartOut).wait(87));

	// text3
	this.instance_2 = new lib.text3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(125.5,130.6);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(21).to({_off:false},0).wait(1).to({regX:96.4,regY:14.2,x:222,y:127.4},0).wait(1).to({x:222.1,y:114.7},0).wait(1).to({x:222.2,y:105.1},0).wait(1).to({y:97.8},0).wait(1).to({x:222.3,y:92.1},0).wait(1).to({y:87.6},0).wait(1).to({y:84.2},0).wait(1).to({x:222.4,y:81.4},0).wait(1).to({y:79.3},0).wait(1).to({y:77.6},0).wait(1).to({y:76.3},0).wait(1).to({regX:0,regY:0,x:126,y:61.1},0).wait(87));

	// text2
	this.instance_3 = new lib.text2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(117.8,36.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(120));

	// text1
	this.instance_4 = new lib.text1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(223.1,18.9,1,1,0,0,0,103.7,23.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(120));

	// product
	this.instance_5 = new lib.product_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(459,37.3,0.5,0.5,0,0,0,150,125);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(21).to({_off:false},0).to({regX:150.2,scaleX:0.72,scaleY:0.72,x:460.1,y:37,alpha:1},12,cjs.Ease.quartOut).wait(87));

	// blue ball
	this.instance_6 = new lib.blueBall();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-181,45.1,0.8,0.8,0,0,0,191,191);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:1.24,scaleY:1.24,x:227},23,cjs.Ease.quartIn).wait(97));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(30.1,-62.7,1062.4,305.6);
// library properties:
lib.properties = {
	id: '191E426E77A9CB4AA443E2CFED2B0FD4',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/product.png?1566821778275", id:"product"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['191E426E77A9CB4AA443E2CFED2B0FD4'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;